### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'

### ISSUE THREAD

**Issue by TianxingWang0** [sattree/gap#3]
Hi, I run setup_all.sh successfully, and when I run the preprocessing command this error shows:

Traceback (most recent call last):
  File "run.py", line 243, in <module>
    main()
  File "run.py", line 239, in main
    force=args.force
  File "run.py", line 54, in run
    coref_models_ = init_coref_models(coref_models)
  File "/gap/models/utils.py", line 55, in init_coref_models
    server.start()
  File "/gap/models/base/utils.py", line 28, in start
    close_fds=True)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'

**Comment by TianxingWang0** [comment]
Oh, I solved it by setting up the java environment.......
